#!/usr/bin/env bash
# Displays a list of currently running processes.
#   Shows all processes, for all users, including those
#+  which might not have a TTY.
# a Bash script that displays a list of currently running processes.

ps -auxf
